version: 2 

models:
  - name: stg_nations
    columns:
      - name: nation_id
        tests:
          - unique
          - not_null
  - name: stg_regions
    columns:
      - name: region_id
        tests:
          - unique
          - not_null       